const PRODUCTS = [
  {
    name: 'Bauernbrot',
    category: 'BREAD',
    unit: 'PIECE',
    weight: 1,
    volume: 0.004,
    price: 3.95,
    shelfLife: 5,
    productionCost: 1.2,
    isSeasonalOnly: false,
  },
  {
    name: 'Kürbiskernbrot',
    category: 'BREAD',
    unit: 'PIECE',
    weight: 0.75,
    volume: 0.003,
    price: 4.2,
    shelfLife: 4,
    productionCost: 1.4,
    isSeasonalOnly: false,
  },
  {
    name: 'Brötchen',
    category: 'ROLLS',
    unit: 'PIECE',
    weight: 0.05,
    volume: 0.0002,
    price: 0.45,
    shelfLife: 1,
    productionCost: 0.15,
    isSeasonalOnly: false,
  },
  {
    name: 'Mehrkornbrötchen',
    category: 'ROLLS',
    unit: 'PIECE',
    weight: 0.06,
    volume: 0.00025,
    price: 0.65,
    shelfLife: 1,
    productionCost: 0.2,
    isSeasonalOnly: false,
  },
  {
    name: 'Laugenbrezel',
    category: 'PRETZEL',
    unit: 'PIECE',
    weight: 0.12,
    volume: 0.0004,
    price: 1.2,
    shelfLife: 1,
    productionCost: 0.35,
    isSeasonalOnly: false,
  },
  {
    name: 'Berliner',
    category: 'PASTRY',
    unit: 'PIECE',
    weight: 0.1,
    volume: 0.0003,
    price: 1.5,
    shelfLife: 2,
    productionCost: 0.45,
    isSeasonalOnly: false,
  },
  {
    name: 'Apfelstrudel',
    category: 'PASTRY',
    unit: 'PIECE',
    weight: 0.25,
    volume: 0.0006,
    price: 2.95,
    shelfLife: 3,
    productionCost: 0.9,
    isSeasonalOnly: false,
  },
  {
    name: 'Mohnkuchen',
    category: 'CAKE',
    unit: 'PIECE',
    weight: 0.15,
    volume: 0.0004,
    price: 2.5,
    shelfLife: 4,
    productionCost: 0.75,
    isSeasonalOnly: false,
  },
  {
    name: 'Bienenstich',
    category: 'CAKE',
    unit: 'PIECE',
    weight: 0.2,
    volume: 0.0005,
    price: 2.75,
    shelfLife: 3,
    productionCost: 0.85,
    isSeasonalOnly: false,
  },
  {
    name: 'Roggenmischbrot',
    category: 'BREAD',
    unit: 'PIECE',
    weight: 0.85,
    volume: 0.0035,
    price: 3.8,
    shelfLife: 5,
    productionCost: 1.15,
    isSeasonalOnly: false,
  },
  {
    name: 'Vollkornbrot',
    category: 'BREAD',
    unit: 'PIECE',
    weight: 0.9,
    volume: 0.0038,
    price: 4.1,
    shelfLife: 6,
    productionCost: 1.3,
    isSeasonalOnly: false,
  },
  {
    name: 'Croissant',
    category: 'PASTRY',
    unit: 'PIECE',
    weight: 0.1,
    volume: 0.0003,
    price: 1.5,
    shelfLife: 2,
    productionCost: 0.45,
    isSeasonalOnly: false,
  },
  {
    name: 'Christstollen',
    category: 'SEASONAL',
    unit: 'PIECE',
    weight: 1.0,
    volume: 0.004,
    price: 12.95,
    shelfLife: 21,
    productionCost: 4.5,
    isSeasonalOnly: true,
  },
  {
    name: 'Osterbrot',
    category: 'SEASONAL',
    unit: 'PIECE',
    weight: 0.75,
    volume: 0.003,
    price: 5.95,
    shelfLife: 5,
    productionCost: 1.8,
    isSeasonalOnly: true,
  },
  {
    name: 'Kürbisbrot',
    category: 'SEASONAL',
    unit: 'PIECE',
    weight: 0.8,
    volume: 0.0035,
    price: 4.5,
    shelfLife: 4,
    productionCost: 1.5,
    isSeasonalOnly: true,
  },
];

module.exports = {
  PRODUCTS,
};
